Repository SciSharp/BotSharp, pull requests merged in 2025-07, with the labels that each got.

#1087 fix realtime toolcall
  src/Plugins/BotSharp.Plugin.DeepSeekAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
Labels: Review effort 2/5

#1091 revert
  src/Infrastructure/BotSharp.Core.SideCar/Services/BotSharpConversationSideCar.cs
Labels: Review effort 2/5

#1094 detour rate limit
  src/Infrastructure/BotSharp.Logger/Hooks/RateLimitConversationHook.cs
Labels: Review effort 2/5

#1093 Refine realtime and twilio
  src/Infrastructure/BotSharp.Abstraction/SideCar/Attributes/SideCarAttribute.cs
  src/Infrastructure/BotSharp.Abstraction/SideCar/IConversationSideCar.cs
  src/Infrastructure/BotSharp.Core.SideCar/Services/BotSharpConversationSideCar.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationStateService.cs
  src/Plugins/BotSharp.Plugin.ChatHub/ChatStreamMiddleware.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/ChatHubConversationHook.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.Twilio/Controllers/TwilioInboundController.cs
Labels: Review effort 2/5

#1098 fix #1097 SqlDriver: Database type mssql is not supported
  src/Plugins/BotSharp.Plugin.SqlDriver/Functions/ExecuteQueryFn.cs
  src/Plugins/BotSharp.Plugin.SqlDriver/Functions/GetTableDefinitionFn.cs
  src/Plugins/BotSharp.Plugin.SqlDriver/Functions/SqlSelect.cs
  src/Plugins/BotSharp.Plugin.SqlDriver/Functions/SqlValidateFn.cs
  src/Plugins/BotSharp.Plugin.SqlDriver/UtilFunctions/GetTableDefinitionFn.cs
  src/Plugins/BotSharp.Plugin.SqlDriver/UtilFunctions/SqlSelect.cs
Labels: Review effort 2/5

#1101 refine message states
  src/Infrastructure/BotSharp.Abstraction/Models/MessageState.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationService.cs
  src/Infrastructure/BotSharp.Logger/Hooks/RateLimitConversationHook.cs
  src/Plugins/BotSharp.Plugin.Twilio/Controllers/TwilioInboundController.cs
  src/Plugins/BotSharp.Plugin.Twilio/OutboundPhoneCallHandler/Functions/OutboundPhoneCallFn.cs
Labels: Review effort 3/5

#1102 Filter conversation by agent ids
  src/Infrastructure/BotSharp.Abstraction/Repositories/Filters/ConversationFilter.cs
  src/Infrastructure/BotSharp.Abstraction/SideCar/Models/SideCarOptions.cs
  src/Infrastructure/BotSharp.Core/Repository/FileRepository/FileRepository.Conversation.cs
  src/Plugins/BotSharp.Plugin.MongoStorage/Repository/MongoRepository.Conversation.cs
Labels: Review effort 2/5

#1105 add channel to the instruct controller
  src/Infrastructure/BotSharp.OpenAPI/Controllers/InstructModeController.cs
Labels: Review effort 2/5

#1107 update router instruction
  src/Infrastructure/BotSharp.Core/data/agents/01fcc3e5-9af7-49e6-ad7a-a760bd12dc4a/instructions/instruction.liquid
Labels: Review effort 2/5

#1103 add invoke source
  src/Infrastructure/BotSharp.Abstraction/Conversations/ConversationHookBase.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/IConversationHook.cs
  src/Infrastructure/BotSharp.Abstraction/Routing/Enums/InvokeSource.cs
  src/Infrastructure/BotSharp.Abstraction/Routing/IRoutingService.cs
  src/Infrastructure/BotSharp.Abstraction/Using.cs
  src/Infrastructure/BotSharp.Core.Realtime/Hooks/RealtimeConversationHook.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationService.SendMessage.cs
  src/Infrastructure/BotSharp.Core/Evaluations/EvaluationConversationHook.cs
  src/Infrastructure/BotSharp.Core/Routing/Reasoning/InstructExecutor.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.InvokeAgent.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.InvokeFunction.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.cs
  src/Infrastructure/BotSharp.Core/Using.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/RealtimeController.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/ChatHubConversationHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/StreamingLogHook.cs
  src/Plugins/BotSharp.Plugin.Twilio/Hooks/TwilioConversationHook.cs
Labels: Review effort 3/5

#1111 add logging in twilio stream
  src/Plugins/BotSharp.Plugin.Twilio/TwilioStreamMiddleware.cs
Labels: Review effort 2/5

#1084 Features/init reactive x
  Directory.Packages.props
  src/Infrastructure/BotSharp.Abstraction/BotSharp.Abstraction.csproj
  src/Infrastructure/BotSharp.Abstraction/Conversations/Dtos/ChatResponseDto.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/IConversationService.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/Models/RoleDialogModel.cs
  src/Infrastructure/BotSharp.Abstraction/MLTasks/IChatCompletion.cs
  src/Infrastructure/BotSharp.Abstraction/Observables/Models/HubObserveData.cs
  src/Infrastructure/BotSharp.Abstraction/Observables/Models/ObserveDataBase.cs
  src/Infrastructure/BotSharp.Abstraction/Routing/IRoutingService.cs
  src/Infrastructure/BotSharp.Core/Conversations/ConversationPlugin.cs
  src/Infrastructure/BotSharp.Core/Demo/Functions/GetWeatherFn.cs
  src/Infrastructure/BotSharp.Core/Infrastructures/Streams/RealtimeTextStream.cs
  src/Infrastructure/BotSharp.Core/Observables/Queues/MessageHub.cs
  src/Infrastructure/BotSharp.Core/Routing/Reasoning/InstructExecutor.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.InvokeAgent.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/ConversationController.cs
  src/Plugins/BotSharp.Plugin.AnthropicAI/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.AzureOpenAI/BotSharp.Plugin.AzureOpenAI.csproj
  src/Plugins/BotSharp.Plugin.AzureOpenAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.ChatHub/ChatHubPlugin.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/ChatHubConversationHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/StreamingLogHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Observers/ChatHubObserver.cs
  src/Plugins/BotSharp.Plugin.DeepSeekAI/BotSharp.Plugin.DeepSeekAI.csproj
  src/Plugins/BotSharp.Plugin.DeepSeekAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Chat/GeminiChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Chat/PalmChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.HuggingFace/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.LLamaSharp/BotSharp.Plugin.LLamaSharp.csproj
  src/Plugins/BotSharp.Plugin.LLamaSharp/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.LangChain/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.MetaGLM/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.MicrosoftExtensionsAI/MicrosoftExtensionsAIChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.SemanticKernel/SemanticKernelChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.SparkDesk/BotSharp.Plugin.SparkDesk.csproj
  src/Plugins/BotSharp.Plugin.SparkDesk/Providers/ChatCompletionProvider.cs
  tests/BotSharp.LLM.Tests/ChatCompletionTests.cs
Labels: Review effort 4/5

#1115 add option agents
  src/Infrastructure/BotSharp.Abstraction/Agents/IAgentService.cs
  src/Infrastructure/BotSharp.Core/Agents/Services/AgentService.RefreshAgents.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/AgentController.cs
  src/Infrastructure/BotSharp.OpenAPI/ViewModels/Agents/Request/AgentMigrationModel.cs
Labels: Review effort 2/5
