Repository SciSharp/BotSharp, pull requests merged in 2025-06, with the labels that each got.

#1076 fix new user login error
  src/Infrastructure/BotSharp.Core/Users/Services/UserService.cs
Labels: Review effort 2/5

#1077 Update webdriver upload files method
  src/Plugins/BotSharp.Plugin.WebDriver/Drivers/PlaywrightDriver/PlaywrightWebDriver.DoAction.cs
Labels: Review effort 3/5

#1078 modify LocateElement logger level
  src/Infrastructure/BotSharp.Abstraction/Browsing/Models/ElementLocatingArgs.cs
  src/Plugins/BotSharp.Plugin.WebDriver/Drivers/PlaywrightDriver/PlaywrightWebDriver.LocateElement.cs
Labels: Review effort 1/5

#1082 fix fork conversation
  src/Infrastructure/BotSharp.Abstraction/Models/MessageState.cs
  src/Infrastructure/BotSharp.Abstraction/SideCar/Attributes/SideCarAttribute.cs
  src/Infrastructure/BotSharp.Abstraction/SideCar/IConversationSideCar.cs
  src/Infrastructure/BotSharp.Core.SideCar/Services/BotSharpConversationSideCar.cs
  src/Infrastructure/BotSharp.Core/Repository/FileRepository/FileRepository.Conversation.cs
  src/Plugins/BotSharp.Plugin.MongoStorage/Repository/MongoRepository.Conversation.cs
  src/Plugins/BotSharp.Plugin.Twilio/OutboundPhoneCallHandler/Functions/OutboundPhoneCallFn.cs
Labels: Review effort 3/5
