Repository SciSharp/BotSharp, pull requests merged in 2025-08, with the labels that each got.

#1116 optimize ConvertToString
  src/Infrastructure/BotSharp.Abstraction/Utilities/StringExtensions.cs
Labels: Review effort 2/5

#1114 refine indication
  src/Infrastructure/BotSharp.Abstraction/Conversations/ConversationHookBase.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/Dtos/ChatResponseDto.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/Enums/ChatEvent.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/IConversationHook.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/IConversationProgressService.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/Models/ConversationSenderActionModel.cs
  src/Infrastructure/BotSharp.Abstraction/Conversations/Models/RoleDialogModel.cs
  src/Infrastructure/BotSharp.Abstraction/MessageHub/Models/HubObserveData.cs
  src/Infrastructure/BotSharp.Abstraction/MessageHub/Models/ObserveDataBase.cs
  src/Infrastructure/BotSharp.Abstraction/MessageHub/Models/ObserverSubscription.cs
  src/Infrastructure/BotSharp.Abstraction/MessageHub/Observers/BotSharpObserverBase.cs
  src/Infrastructure/BotSharp.Abstraction/MessageHub/Observers/IBotSharpObserver.cs
  src/Infrastructure/BotSharp.Abstraction/MessageHub/Services/IObserverService.cs
  src/Infrastructure/BotSharp.Abstraction/Observables/Models/HubObserveData.cs
  src/Infrastructure/BotSharp.Abstraction/Observables/Models/ObserveDataBase.cs
  src/Infrastructure/BotSharp.Abstraction/Routing/IRoutingService.cs
  src/Infrastructure/BotSharp.Abstraction/Routing/Models/InvokeOptions.cs
  src/Infrastructure/BotSharp.Abstraction/SideCar/Attributes/SideCarAttribute.cs
  src/Infrastructure/BotSharp.Abstraction/SideCar/Models/SideCarOptions.cs
  src/Infrastructure/BotSharp.Core.Realtime/Hooks/RealtimeConversationHook.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
  src/Infrastructure/BotSharp.Core.SideCar/Services/BotSharpConversationSideCar.cs
  src/Infrastructure/BotSharp.Core/BotSharp.Core.csproj
  src/Infrastructure/BotSharp.Core/Conversations/ConversationPlugin.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationProgressService.cs
  src/Infrastructure/BotSharp.Core/Demo/Functions/GetFunEventsFn.cs
  src/Infrastructure/BotSharp.Core/Demo/Functions/GetWeatherFn.cs
  src/Infrastructure/BotSharp.Core/Evaluations/EvaluationConversationHook.cs
  src/Infrastructure/BotSharp.Core/MessageHub/MessageHub.cs
  src/Infrastructure/BotSharp.Core/MessageHub/Observers/ConversationObserver.cs
  src/Infrastructure/BotSharp.Core/MessageHub/Services/ObserverService.cs
  src/Infrastructure/BotSharp.Core/MessageHub/Services/ObserverSubscriptionContainer.cs
  src/Infrastructure/BotSharp.Core/Repository/FileRepository/FileRepository.Conversation.cs
  src/Infrastructure/BotSharp.Core/Repository/FileRepository/FileRepository.KnowledgeBase.cs
  src/Infrastructure/BotSharp.Core/Routing/Reasoning/InstructExecutor.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.InvokeAgent.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.InvokeFunction.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingService.cs
  src/Infrastructure/BotSharp.Core/Using.cs
  src/Infrastructure/BotSharp.Core/data/agents/01e2fc5c-2c89-4ec7-8470-7688608b496c/functions/get_fun_events.json
  src/Infrastructure/BotSharp.Core/data/agents/01e2fc5c-2c89-4ec7-8470-7688608b496c/functions/get_weather.json
  src/Infrastructure/BotSharp.OpenAPI/Controllers/ConversationController.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/RealtimeController.cs
  src/Plugins/BotSharp.Plugin.AzureOpenAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.ChatHub/ChatHubPlugin.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Helpers/EventEmitter.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/ChatHubConversationHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/ChatHubCrontabHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/StreamingLogHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/WelcomeHook.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Observers/ChatHubObserver.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Using.cs
  src/Plugins/BotSharp.Plugin.DeepSeekAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.KnowledgeBase/Services/KnowledgeService.Vector.cs
  src/Plugins/BotSharp.Plugin.LLamaSharp/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.SparkDesk/Providers/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.Twilio/Hooks/TwilioConversationHook.cs
  src/Plugins/BotSharp.Plugin.Twilio/Services/TwilioMessageQueueService.cs
Labels: Review effort 4/5

#1085 add chart handler
  BotSharp.sln
  src/Infrastructure/BotSharp.Abstraction/Messaging/BotSharpMessageParser.cs
  src/Infrastructure/BotSharp.Abstraction/Messaging/Enums/RichTypeEnum.cs
  src/Infrastructure/BotSharp.Abstraction/Messaging/Enums/TemplateTypeEnum.cs
  src/Infrastructure/BotSharp.Abstraction/Messaging/Models/RichContent/Template/ProductTemplateMessage.cs
  src/Infrastructure/BotSharp.Abstraction/Messaging/Models/RichContent/Template/ProgramCodeTemplateMessage.cs
  src/Infrastructure/BotSharp.Core/BotSharp.Core.csproj
  src/Infrastructure/BotSharp.Core/Files/Services/Instruct/FileInstructService.SelectFile.cs
  src/Infrastructure/BotSharp.Core/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/templates/util-file-select_file_instruction.liquid
  src/Plugins/BotSharp.Plugin.ChartHandler/BotSharp.Plugin.ChartHandler.csproj
  src/Plugins/BotSharp.Plugin.ChartHandler/ChartHandlerPlugin.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/Enums/UtilityName.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/Functions/PlotChartFn.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/Hooks/ChartHandlerUtilityHook.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/LlmContext/LlmContextIn.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/LlmContext/LlmContextOut.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/Using.cs
  src/Plugins/BotSharp.Plugin.ChartHandler/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/functions/util-chart-plot_chart.json
  src/Plugins/BotSharp.Plugin.ChartHandler/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/templates/util-chart-plot_chart.fn.liquid
  src/Plugins/BotSharp.Plugin.ChartHandler/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/templates/util-chart-plot_instruction.liquid
  src/Plugins/BotSharp.Plugin.FileHandler/BotSharp.Plugin.FileHandler.csproj
  src/Plugins/BotSharp.Plugin.FileHandler/LlmContexts/LlmContextIn.cs
  src/WebStarter/WebStarter.csproj
  src/WebStarter/appsettings.json
Labels: Review effort 3/5, Possible security concern

#1120 add end time
  src/Infrastructure/BotSharp.Abstraction/Repositories/Filters/ConversationFilter.cs
  src/Plugins/BotSharp.Plugin.MongoStorage/Repository/MongoRepository.Conversation.cs
Labels: Review effort 2/5

#1122 Add function to get browser url for Playwright
  src/Infrastructure/BotSharp.Abstraction/Browsing/IWebBrowser.cs
  src/Plugins/BotSharp.Plugin.WebDriver/Drivers/PlaywrightDriver/PlaywrightWebDriver.ExtractData.cs
Labels: Review effort 2/5

#1110 use session in twilio stream
  src/Plugins/BotSharp.Plugin.ChatHub/ChatStreamMiddleware.cs
  src/Plugins/BotSharp.Plugin.Twilio/TwilioStreamMiddleware.cs
Labels: Review effort 3/5

#1129 Features/refine conv filter
  src/Plugins/BotSharp.Plugin.Twilio/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/functions/util-twilio-transfer_phone_call.json
Labels: Review effort 2/5

#1131 add vector payload value operator
  src/Infrastructure/BotSharp.Abstraction/VectorStorage/Models/VectorFilterGroup.cs
  src/Infrastructure/BotSharp.Abstraction/VectorStorage/Models/VectorPayloadValue.cs
  src/Plugins/BotSharp.Plugin.Qdrant/QdrantDb.cs
Labels: Review effort 2/5

#1135 fix vector collection data issue
  src/Infrastructure/BotSharp.Abstraction/VectorStorage/Models/VectorCollectionData.cs
  src/Infrastructure/BotSharp.Abstraction/VectorStorage/Models/VectorSearchResult.cs
  src/Infrastructure/BotSharp.OpenAPI/ViewModels/Knowledges/View/VectorKnowledgeViewModel.cs
  src/Plugins/BotSharp.Plugin.KnowledgeBase/MemVecDb/MemoryVectorDb.cs
  src/Plugins/BotSharp.Plugin.Qdrant/QdrantDb.cs
  src/Plugins/BotSharp.Plugin.SemanticKernel/SemanticKernelMemoryStoreProvider.cs
Labels: Review effort 2/5

#1136 refine web search model select
  src/Infrastructure/BotSharp.Abstraction/MLTasks/Settings/LlmModelSetting.cs
  src/Infrastructure/BotSharp.Core/WebSearch/Functions/WebIntelligentSearchFn.cs
Labels: Review effort 2/5

#1138 refine instruction
  src/Infrastructure/BotSharp.Core/Instructs/Services/InstructService.Execute.cs
Labels: Review effort 2/5
