Repository SciSharp/BotSharp, pull requests merged in 2025-04, with the labels that each got.

#997 Clean code for GeminiLive
  src/Infrastructure/BotSharp.Abstraction/MLTasks/IRealTimeCompletion.cs
  src/Infrastructure/BotSharp.Abstraction/Realtime/Models/RealtimeHubConnection.cs
  src/Infrastructure/BotSharp.Core.Realtime/Hooks/RealtimeConversationHook.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/RealtimeController.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/GoogleAiPlugin.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Chat/GeminiChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Chat/PalmChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Embedding/TextEmbeddingProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/ProviderHelper.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Text/GeminiTextCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Text/PalmTextCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Using.cs
  src/Plugins/BotSharp.Plugin.OpenAI/BotSharp.Plugin.OpenAI.csproj
  src/Plugins/BotSharp.Plugin.OpenAI/Models/Realtime/RealtimeSessionBody.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/Realtime/RealtimeSessionRequest.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/Realtime/RealtimeSessionUpdate.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/SpeechToTextRequest.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/TextCompletionRequest.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/TextCompletionResponse.cs
  src/Plugins/BotSharp.Plugin.OpenAI/OpenAiPlugin.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Chat/ChatCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/IOpenAiRealtimeApi.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Text/TextCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Using.cs
  tests/BotSharp.LLM.Tests/GoogleRealTimeTests.cs
Labels: Review effort 3/5

#1000 Add InterruptResponse in RealtimeModelSettings
  src/Infrastructure/BotSharp.Abstraction/MLTasks/IRealTimeCompletion.cs
  src/Infrastructure/BotSharp.Abstraction/Realtime/IRealtimeHub.cs
  src/Infrastructure/BotSharp.Abstraction/Realtime/Models/RealtimeHubConnection.cs
  src/Infrastructure/BotSharp.Abstraction/Realtime/Models/RealtimeModelSettings.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/Realtime/RealtimeSessionBody.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.Twilio/TwilioStreamMiddleware.cs
Labels: Review effort 2/5

#1003 rename WaveStreamChannel
  src/Infrastructure/BotSharp.Core.Realtime/RealtimePlugin.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/WaveStreamChannel.cs
Labels: Review effort 1/5

#1002 Update Microsoft.Extensions.AI version to 9.4.0-preview.1.25207.5
  Directory.Packages.props
  src/Plugins/BotSharp.Plugin.MicrosoftExtensionsAI/MicrosoftExtensionsAIChatCompletionProvider.cs
Labels: Review effort 2/5

#1004 Fix conversation states before loading agent for init-outbound-call
  src/Plugins/BotSharp.Plugin.Twilio/Controllers/TwilioInboundController.cs
  src/Plugins/BotSharp.Plugin.Twilio/Controllers/TwilioOutboundController.cs
  src/Plugins/BotSharp.Plugin.Twilio/Controllers/TwilioVoiceController.cs
  src/Plugins/BotSharp.Plugin.Twilio/Services/TwilioService.cs
Labels: Review effort 2/5

#1005 function log
  src/Infrastructure/BotSharp.Core.Realtime/Hooks/RealtimeConversationHook.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
Labels: Review effort 2/5

#1006 Features/debug local realtime
  src/Infrastructure/BotSharp.Abstraction/Realtime/IStreamChannel.cs
  src/Infrastructure/BotSharp.Abstraction/Realtime/Models/RealtimeHubConnection.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/WaveStreamChannel.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
  tests/BotSharp.Test.RealtimeVoice/Program.cs
Labels: Review effort 2/5

#1008 add default func
  src/Infrastructure/BotSharp.Abstraction/Realtime/IRealtimeHub.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
Labels: Review effort 2/5

#1009 fix: Google realtime communication
  src/Infrastructure/BotSharp.Core.Realtime/Services/WaveStreamChannel.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Realtime/RealTimeCompletionProvider.cs
  tests/BotSharp.Test.RealtimeVoice/appsettings.json
Labels: Review effort 2/5

#1010 Test/realtime test
  Directory.Packages.props
  src/Infrastructure/BotSharp.Abstraction/Functions/IFunctionCallback.cs
  src/Infrastructure/BotSharp.Abstraction/MCP/Models/McpServerConfigModel.cs
  src/Infrastructure/BotSharp.Abstraction/MCP/Models/McpServerOptionModel.cs
  src/Infrastructure/BotSharp.Abstraction/MCP/Services/IMcpService.cs
  src/Infrastructure/BotSharp.Abstraction/Models/IdName.cs
  src/Infrastructure/BotSharp.Abstraction/Models/MessageState.cs
  src/Infrastructure/BotSharp.Abstraction/Realtime/Models/RealtimeHubConnection.cs
  src/Infrastructure/BotSharp.Abstraction/Utilities/StringExtensions.cs
  src/Infrastructure/BotSharp.Core.MCP/BotSharpMCPExtensions.cs
  src/Infrastructure/BotSharp.Core.MCP/Functions/McpToolAdapter.cs
  src/Infrastructure/BotSharp.Core.MCP/Managers/McpClientManager.cs
  src/Infrastructure/BotSharp.Core.MCP/Services/McpService.cs
  src/Infrastructure/BotSharp.Core.MCP/Settings/MCPSettings.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/RealtimeHub.cs
  src/Infrastructure/BotSharp.Core.Realtime/Services/WaveStreamChannel.cs
  src/Infrastructure/BotSharp.Core/Agents/Services/AgentService.LoadAgent.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationStateService.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationStorage.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/ConversationController.cs
  src/Infrastructure/BotSharp.OpenAPI/Controllers/McpController.cs
  src/Plugins/BotSharp.Plugin.GoogleAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/Realtime/SessionConversationUpdate.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/Session/AiWebsocketPipelineResponse.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/Session/AsyncWebsocketDataCollectionResult.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/Session/AsyncWebsocketDataResultEnumerator.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/Session/RealtimeChatSession.cs
  src/WebStarter/appsettings.json
  tests/BotSharp.PizzaBot.MCPServer/Properties/launchSettings.json
  tests/BotSharp.PizzaBot.MCPServer/Tools/MakePayment.cs
  tests/BotSharp.PizzaBot.MCPServer/Tools/PizzaPrices.cs
  tests/BotSharp.PizzaBot.MCPServer/Tools/PlaceOrder.cs
  tests/BotSharp.Test.RealtimeVoice/Program.cs
  tests/BotSharp.Test.RealtimeVoice/appsettings.json
Labels: Review effort 3/5

#1012 refine init mcp
  src/Infrastructure/BotSharp.Core.MCP/BotSharpMCPExtensions.cs
  src/Infrastructure/BotSharp.Core.MCP/Functions/McpToolAdapter.cs
Labels: Review effort 2/5

#1013 PEOL-187 hotfix System object Disposed Exception: Cannot access a dis…
  src/Infrastructure/BotSharp.Core.Crontab/Services/CrontabEventSubscription.cs
  src/Infrastructure/BotSharp.Core.Crontab/Services/CrontabWatcher.cs
Labels: Review effort 2/5

#1015 fix init states
  src/Infrastructure/BotSharp.OpenAPI/Controllers/ConversationController.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/Session/AsyncWebsocketDataResultEnumerator.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/Session/RealtimeChatSession.cs
Labels: Review effort 2/5

#1017 ResponseDoneStatusDetail
  src/Infrastructure/BotSharp.Core/Routing/Handlers/RouteToAgentRoutingHandler.cs
  src/Infrastructure/BotSharp.Logger/Hooks/VerboseLogHook.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Models/Realtime/ResponseDone.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
Labels: Review effort 2/5

#1018 Remove unnecessary agent load
  src/Infrastructure/BotSharp.Abstraction/Realtime/Models/RealtimeModelSettings.cs
  src/Infrastructure/BotSharp.Core/Agents/Services/AgentService.GetAgents.cs
  src/Infrastructure/BotSharp.Core/Conversations/Services/ConversationStateService.cs
  src/Infrastructure/BotSharp.Core/Routing/RoutingContext.cs
  src/Plugins/BotSharp.Plugin.ChatHub/Hooks/StreamingLogHook.cs
  src/Plugins/BotSharp.Plugin.OpenAI/Providers/Realtime/RealTimeCompletionProvider.cs
  src/Plugins/BotSharp.Plugin.Twilio/OutboundPhoneCallHandler/Functions/HangupPhoneCallFn.cs
  src/Plugins/BotSharp.Plugin.Twilio/Services/TwilioService.cs
Labels: Review effort 2/5

#1016 Add webdriver hook to support file uploads
  src/Infrastructure/BotSharp.Abstraction/Browsing/IWebDriverHook.cs
  src/Infrastructure/BotSharp.Abstraction/Browsing/Models/MessageInfo.cs
  src/Plugins/BotSharp.Plugin.WebDriver/Drivers/PlaywrightDriver/PlaywrightWebDriver.DoAction.cs
  src/Plugins/BotSharp.Plugin.WebDriver/Drivers/PlaywrightDriver/PlaywrightWebDriver.cs
  src/Plugins/BotSharp.Plugin.WebDriver/UtilFunctions/UtilWebActionOnElementFn.cs
  src/Plugins/BotSharp.Plugin.WebDriver/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/functions/util-web-action_on_element.json
Labels: Review effort 2/5

#1026 Add `Triggers` property to `SqlDriverCrontabHook` class
  src/Plugins/BotSharp.Plugin.SqlDriver/Hooks/SqlDriverCrontabHook.cs
Labels: Review effort 1/5

#1028 Refactor Triggered method to return conversation IDs
  src/Infrastructure/BotSharp.Core.Rules/Engines/IRuleEngine.cs
  src/Infrastructure/BotSharp.Core.Rules/Engines/RuleEngine.cs
Labels: Review effort 2/5

#1036 optimize ITwilioCallStatusHook
  src/Infrastructure/BotSharp.Abstraction/Repositories/Filters/ConversationFilter.cs
  src/Infrastructure/BotSharp.Core/Repository/FileRepository/FileRepository.Conversation.cs
  src/Plugins/BotSharp.Plugin.MongoStorage/Repository/MongoRepository.Conversation.cs
  src/Plugins/BotSharp.Plugin.Twilio/Controllers/TwilioVoiceController.cs
  src/Plugins/BotSharp.Plugin.Twilio/Interfaces/ITwilioCallStatusHook.cs
Labels: enhancement

#1040 Update AgentService.GetAgents.cs
  src/Infrastructure/BotSharp.Core/Agents/Services/AgentService.GetAgents.cs
Labels: Review effort 1/5

#1041 Track phone call success state in application
  src/Infrastructure/BotSharp.Abstraction/Infrastructures/Enums/StateConst.cs
  src/Plugins/BotSharp.Plugin.Twilio/OutboundPhoneCallHandler/Functions/OutboundPhoneCallFn.cs
Labels: Review effort 1/5

#1043 Revert "Track phone call success state in application"
  src/Infrastructure/BotSharp.Abstraction/Infrastructures/Enums/StateConst.cs
  src/Plugins/BotSharp.Plugin.Twilio/OutboundPhoneCallHandler/Functions/OutboundPhoneCallFn.cs
Labels: Review effort 1/5

#1039 add function util-crontab-task_wait
  src/Infrastructure/BotSharp.Abstraction/Crontab/Models/TaskWaitArgs.cs
  src/Infrastructure/BotSharp.Core.Crontab/BotSharp.Core.Crontab.csproj
  src/Infrastructure/BotSharp.Core.Crontab/Functions/TaskWaitFn.cs
  src/Infrastructure/BotSharp.Core.Crontab/Hooks/CrontabUtilityHook.cs
  src/Infrastructure/BotSharp.Core.Crontab/data/agents/6745151e-6d46-4a02-8de4-1c4f21c7da95/functions/util-crontab-task_wait.json
Labels: Review effort 2/5
